### PR TITLE
FAI-810: Comprehensive overall to increase Pythonicity

### PR DESCRIPTION
**Pull request by RobGeada**
Changes include:

- trustyai.init() no longer necessary
- Model and ArrowModel subsumed into general Model class
- Model class now accepts numpy and pandas in all forms of predict_fun input and output
- Manual creation of PredictionInputs and PredictionOutputs no longer necessary
- All reference/need to use to Java objects mostly removed
- All original usecases (i.e., all original tests) still work, just deprecated
- Added "universal.py" test to demonstrate new workflow

### CODE REVIEW

**Review by ruivieira — CHANGES_REQUESTED** [review]
@RobGeada, thanks for the PR. A few comments:

https://github.com/trustyai-explainability/trustyai-explainability-python/pull/68/files#diff-d6be3ce558786f5a9cc068f0abede9ef6f40f4b93fd4537670b5153dfa2e78b8R121

I'm not sure about the implicit top-level call to a bare `init()` for a couple of reasons.
First, IIUC, this doesn't really remove the need to initialise, it just replaces `import trustyai ; trustai.init()` with `import trustyai`, even if we don't need the top-level. As an example, in the `universal.py` we still have to `import trustyai`, even if we never use it.
Second, I'm not sure how the `init` with a custom classpath/JAR since `trustyai.init(path=[...])` would never work.

```python
from trustyai import init # calls init()
trustyai.init(path=[]) # already initialised
```

The goal should be to be able to initialise TrustyAI regardless of the import, but also be aware of the cost of having side-effects on imports (e.g. if other JPype library is used, TrustyAI might not work).
Also the docstring does not reflect what's happening.

https://github.com/trustyai-explainability/trustyai-explainability-python/pull/68/files#diff-c83fed0718e261e0138182273770953d45adeca5df196646f1fd9c0660c458b7R65

I t think these names could be more "Pythonic". Perhaps a `@property` and getting rid of `get_*`?

In general, I would also like to see more unit tests (e.g. `_cast_outputs`).

**Comment by RobGeada** [comment]
> @RobGeada, thanks for the PR. A few comments:
> 
> https://github.com/trustyai-explainability/trustyai-explainability-python/pull/68/files#diff-d6be3ce558786f5a9cc068f0abede9ef6f40f4b93fd4537670b5153dfa2e78b8R121
> 
> I'm not sure about the implicit top-level call to a bare `init()` for a couple of reasons. First, IIUC, this doesn't really remove the need to initialise, it just replaces `import trustyai ; trustai.init()` with `import trustyai`, even if we don't need the top-level. As an example, in the `universal.py` we still have to `import trustyai`, even if we never use it. Second, I'm not sure how the `init` with a custom classpath/JAR since `trustyai.init(path=[...])` would never work.
> 
> ```python
> from trustyai import init # calls init()
> trustyai.init(path=[]) # already initialised
> ```
> 
> The goal should be to be able to initialise TrustyAI regardless of the import, but also be aware of the cost of having side-effects on imports (e.g. if other JPype library is used, TrustyAI might not work). Also the docstring does not reflect what's happening.
> 
> https://github.com/trustyai-explainability/trustyai-explainability-python/pull/68/files#diff-c83fed0718e261e0138182273770953d45adeca5df196646f1fd9c0660c458b7R65
> 
> I t think these names could be more "Pythonic". Perhaps a `@property` and getting rid of `get_*`?
> 
> In general, I would also like to see more unit tests (e.g. `_cast_outputs`).

Okay, I've removed the trustyai.init() implicit call; I agree that it was not a good solution to the problem and so I've pushed that off for a future PR. I've added the `@property` for the CFResults proposed features, and added more unit tests to ensure the unified Model class and the more flexible prediction classes are working correctly.

**Review by ruivieira — APPROVED** [review]
LGTM, thanks @RobGeada

**Review by tteofili — APPROVED** [review]
LGTM thanks @RobGeada

**Pull request merged**
